```{r}
library(polynom)
library(elliptic)
library(Rmpfr)
```

```{r}
#Constant
n = 20
start.time<-Sys.time()
w = 0
n0 = 2*n-1
Rp = c()
Ip = c()
number = 0.0;
u = c()
```

```{r}
w = -1
#w(x) function
integrand = function(x,k){
  cos(w*x)*x^k
}
integrand3 = function(x,k){
  sin(w*x)*x^k
}

#u_k values
for (j in 1:(n0+1)){
  integrand2 = function(x){
    integrand(x,(j-1))
  }
  if(j%% 2 ==1){
Rp = c(Rp, integrateR(integrand2, -1, mpfr(1, 128), rel.tol = 1e-128, verbose = TRUE)$value)
  }
  if(j%%2 == 0){
    Rp = c(Rp, mpfr(0, 128))
  }
}

for(j in 1:(n0+1)){
  integrand4 = function(x){
    integrand3(x,(j-1))
  }
  if(j%%2 == 0){
Ip = c(Ip, integrateR(integrand4, -1, mpfr(1, 128), rel.tol = 1e-128, verbose = TRUE)$value)
  }
  if(j%%2 == 1){
    Ip = c(Ip, mpfr(0, 128))
  }
}

new_Rp = c()
new_Ip = c()
for(i in 1 :(n0+1)){
new_Rp = c(new_Rp, as.numeric(sub("\'mpfr1\' ", "", capture.output(Rp[i]@.Data[[1]]))))
new_Ip = c(new_Ip, as.numeric(sub("\'mpfr1\' ", "", capture.output(Ip[i]@.Data[[1]]))))
}

new_u = c()
for(j in 0 : n0){
  number = complex(real = new_Rp[j+1], imaginary = new_Ip[j+1])
  new_u = c(new_u, number)
}

#vector for the matrix
u_data = c()
for(i in 1:n){
  FirstCol = i
  EndCol = n+i-1
  u_data[(n*i-n+1):(n*i)] <- new_u[FirstCol:EndCol]
}
A=matrix(u_data, nrow = n, ncol = n)

#vector for the right part of the equation
FirstCol = n + 1
EndCol = 2*n
b = -new_u[FirstCol:EndCol]

#Output
k = solve(A,b)
k = c(k,1)
Q_eq = polyroot(k)
Q_eq
plot(Q_eq)

end.time <- Sys.time()
time.taken = end.time - start.time
time.taken
```

```{r}
x = 1
```