```{r}
options(digits = 22)

##higher precision needed (64++ decimal)
library(polynom)
library(elliptic)
library(pracma)
#Constant
start.time <- Sys.time()
n =8
w = 1
n0 = 2*n-1
u = c()
val = c()
ic = complex(real = 0, imaginary = 1)

val_1 = 2 / (ic * w) * cos(w) - (2/(ic * w * w)) * sin(w)

val = c(val_1)

moment = 0;
#u_k values
for (j in 2:(2*n-1)){
  a = j %% 2
  if (a == 1){
    moment = (2/(ic*w) * cos(w) - j / (ic * w) * val[j-1])
    val = c(val, moment)
  }
  else if (a == 0){
    moment = (2 / w * sin(w) - j / (ic * w) * val[j-1])
    val = c(val, moment)
  }
}

val

val_0 = 2 / w * sin(w)

verti = c(val_0)
for(j in 1:n-1){
   verti = c(verti, val[j])
}

hori = c()
for(j in (n-1):(2*n-2)){
  hori = c(hori, val[j])
}

last = c()
for (j in n:(2*n-1)){
  k = (-1) * val[j]
  last = c(last, k)
}

last

H = hankel(verti, hori)

L = solve(H, last)
k = c(L, 1)
Q_eq = polyroot(k)
plot(Q_eq)
```

```{r}
Q_eq
end.time <- Sys.time()
time.taken <- end.time - start.time
time.taken
```

```{r}
cond(H, p = 2)
```




