```{r}
##If you want to run this code, click the second right button at the bottommost (Button next to the wheel)
##Change n and w. Change precision if needed. Save the graph by right clicking the graph.
##Don't forget to save the n, w, precision and run time in the file name!!
library(polynom)
library(elliptic)
library(Rmpfr)
time.taken = c()
n = 1                  ##<----Here you can change n
for(w in 1:5){         ##<----Here you can change w
start.time <- Sys.time()
n0 = 2*n-1
Rp = c()
Ip = c()
number = 0.0;
u = c()

#integrate function
integrand = function(x,k){
  cos(w*x)*x^k
}
integrand3 = function(x,k){
  sin(w*x)*x^k
}

#Real part integration
for (j in 0:n0){
  integrand2 = function(x){                 ##Here you can change the precision (I think we have to change both)
    integrand(x,j)                          ## |                |
  }                                         ## v                V
Rp = c(Rp, integrateR(integrand2, -1, mpfr(1, 16), rel.tol = 1e-16, verbose = TRUE)$value)
}

##Imaginary part integration
for(j in 0:n0){
  integrand4 = function(x){                 ##Here you can change the precision (I think we have to change both)
    integrand(x,j)                          ## |                |
  }                                         ## v                V
Ip = c(Ip, integrateR(integrand4, -1, mpfr(1, 16), rel.tol = 1e-16, verbose = TRUE)$value)
}

##converting
new_Rp = c()
new_Ip = c()
for(i in 1 :(n0+1)){
new_Rp = c(new_Rp, as.numeric(sub("\'mpfr1\' ", "", capture.output(Rp[i]@.Data[[1]]))))
new_Ip = c(new_Ip, as.numeric(sub("\'mpfr1\' ", "", capture.output(Ip[i]@.Data[[1]]))))
}
##From here, our number is class double, not mpfr1 (Have lower precision)

##combining
new_u = c()
for(j in 0 : n0){
  number = complex(real = new_Rp[j+1], imaginary = new_Ip[j+1])
  new_u = c(new_u, number)
}

#vector for the matrix
u_data = c()
for(i in 1:n){
  FirstCol = i
  EndCol = n+i-1
  u_data[(n*i-n+1):(n*i)] <- new_u[FirstCol:EndCol]
}
A=matrix(u_data, nrow = n, ncol = n)

#vector for the right part of the equation
FirstCol = n + 1
EndCol = 2*n
b = -new_u[FirstCol:EndCol]

#Output
k = solve(A,b)
k = c(k,1)
Q_eq = polyroot(k)
Q_eq
plot(Q_eq)
end.time <- Sys.time()
time.taken <- c(time.taken, end.time - start.time)
}
```

```{r}
time.taken
```
```{r}
x = 1
```

