```{r}
##higher precision needed (64++ decimal)
library(polynom)
library(elliptic)
library(Rmpfr)
library(pracma)
#Constant
n = 50
w = mpfr(20, 256L)
ic = complex(real = 0, imaginary = 1)
n0 = 2*n-1
u = c()
val = c()

val_1 = mpfr(-2 / (w) * cos(w) + (2/(w * w)) * sin(w), 128L)
val = c(val, val_1)
kxx = sub("\'mpfr1\' ", "", capture.output(val[1]@.Data[[1]]))
```

```{r}
complex(real = mpfr(0, 128), imaginary = mpfr(-2 / (w) * cos(w) + (2/(w * w)) * sin(w), 128))
```
```{r}
val_1 = complex(real = 0, imaginary = as.numeric(sub("\'mpfr1\' ", "", capture.output(val_1@.Data[[1]]))))
val = c(val_1)
moment = 0;
val_1
```

```{r}

#u_k values
for (j in 2:(2*n-1)){
  a = j %% 2
  if (a == 0){
    moment = mpfr(2 / w * sin(w) - j / (w) * Im(val[j-1]), 128L)
    moment = complex(real = as.numeric(sub("\'mpfr1\' ", "", capture.output(moment@.Data[[1]]))), imaginary = 0)
    val = c(val, moment)
  }
  else if (a == 1){
    moment = mpfr(-2/ (w) * cos(w) + j / (w) * Re(val[j-1]), 128L)
    moment = complex(real= 0, imaginary = as.numeric(sub("\'mpfr1\' ", "", capture.output(moment@.Data[[1]]))))
    val = c(val, moment)
  }
  
}
```
```{r}
val[1]
```
```{r}
val_0 = 2 / w * sin(w)
val_0 = as.numeric(sub("\'mpfr1\' ", "", capture.output(val_0@.Data[[1]])))
```

```{r}
verti = c(val_0)
for(j in 1:n-1){
   verti = c(verti, val[j])
}

hori = c()
for(j in (n-1):(2*n-2)){
  hori = c(hori, val[j])
}

last = c()
for (j in n:(2*n-1)){
  k = (-1) * val[j]
  last = c(last, k)
}
```

```{r}
last
```

```{r}
H = hankel(verti, hori)
```
```{r}
L = solve(H, last)
k = c(L, 1)
Q_eq = polyroot(k)
plot(Q_eq)
```

```{r}
Q_eq
```